version: '3'
services:
  db:
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_DATABASE: 'testBase'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - test-db:/var/lib/mysql
volumes:
  test-db: